
-- CREATE DATABASE IF NOT EXISTS wordbase CHARACTER SET utf8 COLLATE utf8_bin;

-- DROP TABLE IF EXISTS
--      CHARACTER_LIST_LEVEL_0, CHARACTER_LIST_LEVEL_1,CHARACTER_LIST_LEVEL_2,WORD_LIST_LEVEL_0,PINYIN_LIST_ALL; 
/**THE TOTAL SET OF CHARACTERS IN CHINESE. IT DERIVES THE LEVEL_1 AND LEVEL_2 CHARACTER SET BASED ON STATISTICS*/
CREATE TABLE IF NOT EXISTS
    CHARACTER_LIST_LEVEL_0(
            UNICODE         INT     NOT NULL    COMMENT 'UNICODE OF THE CHARACTER, INTEGER NUMBER IS PORTABLE FOR ALL DBs',
            LITERAL         VARCHAR(1)      COMMENT 'CHARACTER THE SAME AS THE UNICODE_1 REPRESENTATION',
            FREQUENCY       BIGINT  DEFAULT 0   COMMENT 'FREQUENCY_1 FOR UNICODE_1, FREQUENCY OF THE CHARACTER IN CORPUS',
            STRING          VARCHAR(100)    COMMENT 'TEXT FOR EXTRA CORPUS',
            RATE_1         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_2         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_3         DOUBLE(15,12)   DEFAULT 0.0,
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            SPELL_1        VARCHAR(20),
            SPELL_2        VARCHAR(20),
            SPELL_3        VARCHAR(20),
            SPELL_4        VARCHAR(20),
            SPELL_5        VARCHAR(20),
            SPELL_6        VARCHAR(20),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(UNICODE),
            UNIQUE INDEX UNIC_FREQ USING HASH(UNICODE, FREQUENCY),
            UNIQUE INDEX UNIC USING HASH (UNICODE),
            INDEX LITR_FREQ USING HASH(LITERAL, FREQUENCY),
            INDEX LITR USING HASH (LITERAL),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX RATE USING BTREE (RATE_1, RATE_2, RATE_3) 
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'BASIC CHARACTER SET FOR NEARLY ALL CHARACTERS IN CHINESE';

ALTER TABLE CHARACTER_LIST_LEVEL_0 CHANGE LITERAL LITERAL VARCHAR(1) CHARACTER SET utf8 COLLATE utf8_bin;

/**THE CHARACTERS MORE FREQUENTLY USED THAN LEVEL_0, BUT LESS THAN LEVEL_2,3,N. CURRENTLY, IT CONTAINS CHARACTERS IN
COMMONLY USED CHINESE CHARACTER LEVEL 2, 1000 CHARACTERS.*/            
CREATE TABLE IF NOT EXISTS
    CHARACTER_LIST_LEVEL_1(
            UNICODE         INT     NOT NULL    COMMENT 'UNICODE OF THE CHARACTER, INTEGER NUMBER IS PORTABLE FOR ALL DBs',
            LITERAL         VARCHAR(1)      COMMENT 'CHARACTER THE SAME AS THE UNICODE_1 REPRESENTATION',
            FREQUENCY       BIGINT  DEFAULT 0   COMMENT 'FREQUENCY_1 FOR UNICODE_1, FREQUENCY OF THE CHARACTER IN CORPUS',
            STRING          VARCHAR(100)    COMMENT 'TEXT FOR EXTRA CORPUS',
            RATE_1         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_2         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_3         DOUBLE(15,12)   DEFAULT 0.0,
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            SPELL_1        VARCHAR(20),
            SPELL_2        VARCHAR(20),
            SPELL_3        VARCHAR(20),
            SPELL_4        VARCHAR(20),
            SPELL_5        VARCHAR(20),
            SPELL_6        VARCHAR(20),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(UNICODE),
            UNIQUE INDEX UNIC_FREQ USING HASH(UNICODE, FREQUENCY),
            UNIQUE INDEX UNIC USING HASH (UNICODE),
            INDEX LITR_FREQ USING HASH(LITERAL, FREQUENCY),
            INDEX LITR USING HASH (LITERAL),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX RATE USING BTREE (RATE_1, RATE_2, RATE_3) 
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'LEVEL 1 CHARACTER SET FOR FREQUENTLY USED CHINESE LEVEL 1';
/**COMMONLY USED CHARACTERS LEVEL 1, 2500 CHARACTERS*/            
CREATE TABLE IF NOT EXISTS
    CHARACTER_LIST_LEVEL_2(
            UNICODE         INT     NOT NULL    COMMENT 'UNICODE OF THE CHARACTER, INTEGER NUMBER IS PORTABLE FOR ALL DBs',
            LITERAL         VARCHAR(1)      COMMENT 'CHARACTER THE SAME AS THE UNICODE_1 REPRESENTATION',
            FREQUENCY       BIGINT  DEFAULT 0   COMMENT 'FREQUENCY_1 FOR UNICODE_1, FREQUENCY OF THE CHARACTER IN CORPUS',
            STRING          VARCHAR(100)    COMMENT 'TEXT FOR EXTRA CORPUS',
            RATE_1         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_2         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_3         DOUBLE(15,12)   DEFAULT 0.0,
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            SPELL_1        VARCHAR(20),
            SPELL_2        VARCHAR(20),
            SPELL_3        VARCHAR(20),
            SPELL_4        VARCHAR(20),
            SPELL_5        VARCHAR(20),
            SPELL_6        VARCHAR(20),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(UNICODE),
            UNIQUE INDEX UNIC_FREQ USING HASH(UNICODE, FREQUENCY),
            UNIQUE INDEX UNIC USING HASH (UNICODE),
            INDEX LITR_FREQ USING HASH(LITERAL, FREQUENCY),
            INDEX LITR USING HASH (LITERAL),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX RATE USING BTREE (RATE_1, RATE_2, RATE_3) 
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'LEVEL 2 CHARACTER SET FOR FREQUENTLY USED CHINESE LEVEL 2';

-- CHINESE PUNCTUATION
CREATE TABLE IF NOT EXISTS
    CHARACTER_LIST_LEVEL_3(
            UNICODE         INT     NOT NULL    COMMENT 'UNICODE OF THE CHARACTER, INTEGER NUMBER IS PORTABLE FOR ALL DBs',
            LITERAL         VARCHAR(1)      COMMENT 'CHARACTER THE SAME AS THE UNICODE_1 REPRESENTATION',
            FREQUENCY       BIGINT  DEFAULT 0   COMMENT 'FREQUENCY_1 FOR UNICODE_1, FREQUENCY OF THE CHARACTER IN CORPUS',
            STRING          VARCHAR(100)    COMMENT 'TEXT FOR EXTRA CORPUS',
            RATE_1         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_2         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_3         DOUBLE(15,12)   DEFAULT 0.0,
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            SPELL_1        VARCHAR(20),
            SPELL_2        VARCHAR(20),
            SPELL_3        VARCHAR(20),
            SPELL_4        VARCHAR(20),
            SPELL_5        VARCHAR(20),
            SPELL_6        VARCHAR(20),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(UNICODE),
            UNIQUE INDEX UNIC_FREQ USING HASH(UNICODE, FREQUENCY),
            UNIQUE INDEX UNIC USING HASH (UNICODE),
            INDEX LITR_FREQ USING HASH(LITERAL, FREQUENCY),
            INDEX LITR USING HASH (LITERAL),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX RATE USING BTREE (RATE_1, RATE_2, RATE_3) 
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'CHARACTER SET FOR PUNCTUATION';

-- AUXILIARY WORD
CREATE TABLE IF NOT EXISTS
    CHARACTER_LIST_LEVEL_4(
            UNICODE         INT     NOT NULL    COMMENT 'UNICODE OF THE CHARACTER, INTEGER NUMBER IS PORTABLE FOR ALL DBs',
            LITERAL         VARCHAR(1)      COMMENT 'CHARACTER THE SAME AS THE UNICODE_1 REPRESENTATION',
            FREQUENCY       BIGINT  DEFAULT 0   COMMENT 'FREQUENCY_1 FOR UNICODE_1, FREQUENCY OF THE CHARACTER IN CORPUS',
            STRING          VARCHAR(100)    COMMENT 'TEXT FOR EXTRA CORPUS',
            RATE_1         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_2         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_3         DOUBLE(15,12)   DEFAULT 0.0,
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            SPELL_1        VARCHAR(20),
            SPELL_2        VARCHAR(20),
            SPELL_3        VARCHAR(20),
            SPELL_4        VARCHAR(20),
            SPELL_5        VARCHAR(20),
            SPELL_6        VARCHAR(20),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(UNICODE),
            UNIQUE INDEX UNIC_FREQ USING HASH(UNICODE, FREQUENCY),
            UNIQUE INDEX UNIC USING HASH (UNICODE),
            INDEX LITR_FREQ USING HASH(LITERAL, FREQUENCY),
            INDEX LITR USING HASH (LITERAL),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX RATE USING BTREE (RATE_1, RATE_2, RATE_3) 
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'CHARACTER SET FOR AUXILIARY WORD';


-- AUXILIARY WORD LEVEL_1, THE REFINED AUXILIARY WORD
CREATE TABLE IF NOT EXISTS
    CHARACTER_LIST_LEVEL_5(
            UNICODE         INT     NOT NULL    COMMENT 'UNICODE OF THE CHARACTER, INTEGER NUMBER IS PORTABLE FOR ALL DBs',
            LITERAL         VARCHAR(5)      COMMENT 'CHARACTER THE SAME AS THE UNICODE_1 REPRESENTATION',
            FREQUENCY       BIGINT  DEFAULT 0   COMMENT 'FREQUENCY_1 FOR UNICODE_1, FREQUENCY OF THE CHARACTER IN CORPUS',
            STRING          VARCHAR(100)    COMMENT 'TEXT FOR EXTRA CORPUS',
            RATE_1         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_2         DOUBLE(15,12)   DEFAULT 0.0,
            RATE_3         DOUBLE(15,12)   DEFAULT 0.0,
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            SPELL_1        VARCHAR(20),
            SPELL_2        VARCHAR(20),
            SPELL_3        VARCHAR(20),
            SPELL_4        VARCHAR(20),
            SPELL_5        VARCHAR(20),
            SPELL_6        VARCHAR(20),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(UNICODE),
            UNIQUE INDEX UNIC_FREQ USING HASH(UNICODE, FREQUENCY),
            UNIQUE INDEX UNIC USING HASH (UNICODE),
            INDEX LITR_FREQ USING HASH(LITERAL, FREQUENCY),
            INDEX LITR USING HASH (LITERAL),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX RATE USING BTREE (RATE_1, RATE_2, RATE_3) 
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'CHARACTER SET FOR AUXILIARY WORD, LEVEL_1, THE REFINED AUXILIARY WORD';


CREATE TABLE IF NOT EXISTS
    WORD_LIST_LEVEL_0(
            ID              BIGINT  AUTO_INCREMENT  NOT NULL,
            FREQUENCY       BIGINT DEFAULT 0,
            CONTENT         VARCHAR(15),
            HASH_1         BIGINT UNSIGNED NOT NULL,
            HASH_2         BIGINT UNSIGNED,
            HASH_3         BIGINT UNSIGNED,
            HASH_4         BIGINT UNSIGNED,
            RATE_1         DOUBLE(15,12),
            RATE_2         DOUBLE(15,12),
            RATE_3         DOUBLE(15,12),
            RATE_4         DOUBLE(15,12),
            RATE_5         DOUBLE(15,12),
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            NUMB_4         INT,
            NUMB_5         INT,
            UNICODE_1      INT NOT NULL,
            UNICODE_2      INT,
            UNICODE_3      INT,
            UNICODE_4      INT,
            UNICODE_5      INT,
            UNICODE_6      INT,
            UNICODE_7      INT,
            UNICODE_8      INT,
            UNICODE_9      INT,
            UNICODE_10      INT,
            UNICODE_11      INT,
            UNICODE_12      INT,
            UNICODE_13      INT,
            UNICODE_14      INT,
            UNICODE_15      INT,
            LITERAL_1      VARCHAR(1),
            LITERAL_2      VARCHAR(1),
            LITERAL_3      VARCHAR(1),
            LITERAL_4      VARCHAR(1),
            LITERAL_5      VARCHAR(1),
            LITERAL_6      VARCHAR(1),
            LITERAL_7      VARCHAR(1),
            LITERAL_8      VARCHAR(1),
            LITERAL_9      VARCHAR(1),
            LITERAL_10      VARCHAR(1),
            LITERAL_11      VARCHAR(1),
            LITERAL_12      VARCHAR(1),
            LITERAL_13      VARCHAR(1),
            LITERAL_14      VARCHAR(1),
            LITERAL_15      VARCHAR(1),
            SPELL_1        VARCHAR(100),
            SPELL_2        VARCHAR(100),
            SPELL_3        VARCHAR(100),
            SPELL_4        VARCHAR(100),
            SPELL_5        VARCHAR(100),
            SPELL_6        VARCHAR(100),
            STRING_1       VARCHAR(100),
            STRING_2       VARCHAR(100),
            STRING_3       VARCHAR(100),
            STRING_4       VARCHAR(100),
            STRING_5       VARCHAR(100),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(ID),
            INDEX UNIC1 USING BTREE (
                        UNICODE_1, 
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR1 USING BTREE (
                        LITERAL_1, 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC2 USING BTREE (
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR2 USING BTREE ( 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC3 USING BTREE (
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR3 USING BTREE (
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC4 USING BTREE (
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR4 USING BTREE (
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC5 USING BTREE (
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR5 USING BTREE (
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC6 USING BTREE (
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR6 USING BTREE (
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC7 USING BTREE (
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR7 USING BTREE (
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC8 USING BTREE (
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR8 USING BTREE (
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC9 USING BTREE (
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR9 USING BTREE (
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC10 USING BTREE (UNICODE_10),
            INDEX LITR10 USING BTREE (LITERAL_10),
            INDEX FREQ  USING BTREE (FREQUENCY),
            INDEX RATE  USING BTREE (
                        RATE_1,
                        RATE_2,
                        RATE_3,
                        RATE_4,
                        RATE_5)
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'ALL WORDS IN USE';

CREATE INDEX WORD_HASH USING HASH ON WORD_LIST_LEVEL_0(CONTENT);            
CREATE INDEX WORD_BTREE USING BTREE ON WORD_LIST_LEVEL_0(CONTENT);
CREATE INDEX HASH1 USING HASH ON WORD_LIST_LEVEL_0(HASH_1);
CREATE INDEX HASH2 USING HASH ON WORD_LIST_LEVEL_0(HASH_2);
CREATE INDEX HASH3 USING HASH ON WORD_LIST_LEVEL_0(HASH_3);
CREATE INDEX HASH4 USING HASH ON WORD_LIST_LEVEL_0(HASH_4);


-- REFINED WORDS, NOT THE RAW WORDS

CREATE TABLE IF NOT EXISTS
    WORD_LIST_LEVEL_1(
            ID              BIGINT,
            FREQUENCY       BIGINT DEFAULT 0,
            CONTENT         VARCHAR(15),
            HASH_1         BIGINT UNSIGNED NOT NULL,
            HASH_2         BIGINT UNSIGNED,
            HASH_3         BIGINT UNSIGNED,
            HASH_4         BIGINT UNSIGNED,
            RATE_1         DOUBLE(15,12),
            RATE_2         DOUBLE(15,12),
            RATE_3         DOUBLE(15,12),
            RATE_4         DOUBLE(15,12),
            RATE_5         DOUBLE(15,12),
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            NUMB_4         INT,
            NUMB_5         INT,
            UNICODE_1      INT NOT NULL,
            UNICODE_2      INT,
            UNICODE_3      INT,
            UNICODE_4      INT,
            UNICODE_5      INT,
            UNICODE_6      INT,
            UNICODE_7      INT,
            UNICODE_8      INT,
            UNICODE_9      INT,
            UNICODE_10      INT,
            UNICODE_11      INT,
            UNICODE_12      INT,
            UNICODE_13      INT,
            UNICODE_14      INT,
            UNICODE_15      INT,
            LITERAL_1      VARCHAR(1),
            LITERAL_2      VARCHAR(1),
            LITERAL_3      VARCHAR(1),
            LITERAL_4      VARCHAR(1),
            LITERAL_5      VARCHAR(1),
            LITERAL_6      VARCHAR(1),
            LITERAL_7      VARCHAR(1),
            LITERAL_8      VARCHAR(1),
            LITERAL_9      VARCHAR(1),
            LITERAL_10      VARCHAR(1),
            LITERAL_11      VARCHAR(1),
            LITERAL_12      VARCHAR(1),
            LITERAL_13      VARCHAR(1),
            LITERAL_14      VARCHAR(1),
            LITERAL_15      VARCHAR(1),
            SPELL_1        VARCHAR(100),
            SPELL_2        VARCHAR(100),
            SPELL_3        VARCHAR(100),
            SPELL_4        VARCHAR(100),
            SPELL_5        VARCHAR(100),
            SPELL_6        VARCHAR(100),
            STRING_1       VARCHAR(100),
            STRING_2       VARCHAR(100),
            STRING_3       VARCHAR(100),
            STRING_4       VARCHAR(100),
            STRING_5       VARCHAR(100),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            INDEX UNIC1 USING BTREE (
                        UNICODE_1, 
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR1 USING BTREE (
                        LITERAL_1, 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC2 USING BTREE (
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR2 USING BTREE ( 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC3 USING BTREE (
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR3 USING BTREE (
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC4 USING BTREE (
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR4 USING BTREE (
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC5 USING BTREE (
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR5 USING BTREE (
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC6 USING BTREE (
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR6 USING BTREE (
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC7 USING BTREE (
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR7 USING BTREE (
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC8 USING BTREE (
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR8 USING BTREE (
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC9 USING BTREE (
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR9 USING BTREE (
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC10 USING BTREE (UNICODE_10),
            INDEX LITR10 USING BTREE (LITERAL_10),
            INDEX FREQ  USING BTREE (FREQUENCY),
            INDEX RATE  USING BTREE (
                        RATE_1,
                        RATE_2,
                        RATE_3,
                        RATE_4,
                        RATE_5)
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'ALL WORDS IN USE, REFINED.';

CREATE INDEX WORD_HASH USING HASH ON WORD_LIST_LEVEL_1(CONTENT);            
CREATE INDEX WORD_BTREE USING BTREE ON WORD_LIST_LEVEL_1(CONTENT);
CREATE INDEX HASH1 USING HASH ON WORD_LIST_LEVEL_1(HASH_1);
CREATE INDEX HASH2 USING HASH ON WORD_LIST_LEVEL_1(HASH_2);
CREATE INDEX HASH3 USING HASH ON WORD_LIST_LEVEL_1(HASH_3);
CREATE INDEX HASH4 USING HASH ON WORD_LIST_LEVEL_1(HASH_4);


-- DUMPED WORDS
CREATE TABLE IF NOT EXISTS
    WORD_LIST_LEVEL_2(
            ID              BIGINT,
            FREQUENCY       BIGINT DEFAULT 0,
            CONTENT         VARCHAR(15),
            HASH_1         BIGINT UNSIGNED NOT NULL,
            HASH_2         BIGINT UNSIGNED,
            HASH_3         BIGINT UNSIGNED,
            HASH_4         BIGINT UNSIGNED,
            RATE_1         DOUBLE(15,12),
            RATE_2         DOUBLE(15,12),
            RATE_3         DOUBLE(15,12),
            RATE_4         DOUBLE(15,12),
            RATE_5         DOUBLE(15,12),
            NUMB_1         INT,
            NUMB_2         INT,
            NUMB_3         INT,
            NUMB_4         INT,
            NUMB_5         INT,
            UNICODE_1      INT NOT NULL,
            UNICODE_2      INT,
            UNICODE_3      INT,
            UNICODE_4      INT,
            UNICODE_5      INT,
            UNICODE_6      INT,
            UNICODE_7      INT,
            UNICODE_8      INT,
            UNICODE_9      INT,
            UNICODE_10      INT,
            UNICODE_11      INT,
            UNICODE_12      INT,
            UNICODE_13      INT,
            UNICODE_14      INT,
            UNICODE_15      INT,
            LITERAL_1      VARCHAR(1),
            LITERAL_2      VARCHAR(1),
            LITERAL_3      VARCHAR(1),
            LITERAL_4      VARCHAR(1),
            LITERAL_5      VARCHAR(1),
            LITERAL_6      VARCHAR(1),
            LITERAL_7      VARCHAR(1),
            LITERAL_8      VARCHAR(1),
            LITERAL_9      VARCHAR(1),
            LITERAL_10      VARCHAR(1),
            LITERAL_11      VARCHAR(1),
            LITERAL_12      VARCHAR(1),
            LITERAL_13      VARCHAR(1),
            LITERAL_14      VARCHAR(1),
            LITERAL_15      VARCHAR(1),
            SPELL_1        VARCHAR(100),
            SPELL_2        VARCHAR(100),
            SPELL_3        VARCHAR(100),
            SPELL_4        VARCHAR(100),
            SPELL_5        VARCHAR(100),
            SPELL_6        VARCHAR(100),
            STRING_1       VARCHAR(100),
            STRING_2       VARCHAR(100),
            STRING_3       VARCHAR(100),
            STRING_4       VARCHAR(100),
            STRING_5       VARCHAR(100),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            INDEX UNIC1 USING BTREE (
                        UNICODE_1, 
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR1 USING BTREE (
                        LITERAL_1, 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC2 USING BTREE (
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR2 USING BTREE ( 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC3 USING BTREE (
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR3 USING BTREE (
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC4 USING BTREE (
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR4 USING BTREE (
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC5 USING BTREE (
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR5 USING BTREE (
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC6 USING BTREE (
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR6 USING BTREE (
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC7 USING BTREE (
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR7 USING BTREE (
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC8 USING BTREE (
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR8 USING BTREE (
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC9 USING BTREE (
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR9 USING BTREE (
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC10 USING BTREE (UNICODE_10),
            INDEX LITR10 USING BTREE (LITERAL_10),
            INDEX FREQ  USING BTREE (FREQUENCY),
            INDEX RATE  USING BTREE (
                        RATE_1,
                        RATE_2,
                        RATE_3,
                        RATE_4,
                        RATE_5)
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'THE WORDS DUMPED.';
CREATE INDEX WORD_HASH USING HASH ON WORD_LIST_LEVEL_2(CONTENT);            
CREATE INDEX WORD_BTREE USING BTREE ON WORD_LIST_LEVEL_2(CONTENT);
CREATE INDEX HASH1 USING HASH ON WORD_LIST_LEVEL_2(HASH_1);
CREATE INDEX HASH2 USING HASH ON WORD_LIST_LEVEL_2(HASH_2);
CREATE INDEX HASH3 USING HASH ON WORD_LIST_LEVEL_2(HASH_3);
CREATE INDEX HASH4 USING HASH ON WORD_LIST_LEVEL_2(HASH_4);

-- DROP TABLE IF EXISTS PINYIN_LIST_ALL;            
CREATE TABLE IF NOT EXISTS
        PINYIN_LIST_ALL (
            UNICODE     BIGINT NOT NULL,
            PINYIN      VARCHAR(20),
            WORD        VARCHAR(10),
            PYHASH_1   BIGINT UNSIGNED NOT NULL,
            PYHASH_2   BIGINT UNSIGNED,
            PYHASH_3   BIGINT UNSIGNED,
            PYHASH_4   BIGINT UNSIGNED,
            WDHASH_1   BIGINT UNSIGNED NOT NULL,
            WDHASH_2   BIGINT UNSIGNED,
            WDHASH_3   BIGINT UNSIGNED,
            WDHASH_4   BIGINT UNSIGNED,
            NUMB_1     INT,
            NUMB_2     INT,
            NUMB_3     INT,
            PY_1       INT     COMMENT 'UNICODE FOR THE PHONYM',
            PY_2       INT,
            PY_3       INT,
            PY_4       INT,
            PY_5       INT,
            PY_6       INT,
            PY_7       INT,
            PY_8       INT,
            PY_9       INT,
            PY_10       INT,
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            INDEX UNIC USING BTREE (UNICODE),
            INDEX WORD_HASH USING HASH (WORD),
            INDEX WORD_BTREE USING BTREE (WORD),
            INDEX PINY_HASH USING HASH (PINYIN),
            INDEX PINY_BTREE USING BTREE (PINYIN),
            INDEX UNIC_WORD USING BTREE (UNICODE, WORD),
            INDEX WORD_UNIC USING BTREE (WORD, UNICODE),
            INDEX UNIC_PINY USING BTREE (UNICODE, PINYIN),
            INDEX WORD_PINY USING BTREE (WORD, PINYIN),
            INDEX ALL_INDEX USING BTREE (UNICODE, WORD, PINYIN),
            INDEX PYHASH1 USING HASH (PYHASH_1),
            INDEX PYHASH2 USING HASH (PYHASH_2),
            INDEX WDHASH1 USING HASH (WDHASH_1),
            INDEX WDHASH2 USING HASH (WDHASH_2),
            INDEX PYWDHASH1 USING HASH (PYHASH_1, WDHASH_1),
            INDEX PYWDHASH2 USING HASH (PYHASH_2, WDHASH_2),
            INDEX PYWDHASH  USING HASH (PYHASH_1, PYHASH_2, WDHASH_1, WDHASH_2)
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'UNICODE IN WORD SHOULD HAVE PINYIN IN USE';

-- DROP TABLE IF EXISTS IDIOM_LIST_LEVEL_0;            
CREATE TABLE IF NOT EXISTS 
        IDIOM_LIST_LEVEL_0 (
            ID          BIGINT NOT NULL AUTO_INCREMENT,
            HASH_1  BIGINT UNSIGNED NOT NULL,
            HASH_2  BIGINT UNSIGNED,
            HASH_3  BIGINT UNSIGNED,
            HASH_4  BIGINT UNSIGNED,
            CONTENT      VARCHAR(10) NOT NULL,
            FREQUENCY   BIGINT,
            FREQ_1     BIGINT,
            FREQ_2     BIGINT,
            FREQ_3     BIGINT,
            FREQ_4     BIGINT,
            FREQ_5     BIGINT,
            NUMB_1     INT,
            NUMB_2     INT,
            NUMB_3     INT,
            NUMB_4     INT,
            NUMB_5     INT,
            RATE_1     DOUBLE(15,12),
            RATE_2     DOUBLE(15,12),
            RATE_3     DOUBLE(15,12),
            RATE_4     DOUBLE(15,12),
            RATE_5     DOUBLE(15,12),
            UNICODE_1  INT NOT NULL,
            UNICODE_2  INT,
            UNICODE_3  INT,
            UNICODE_4  INT,
            UNICODE_5  INT,
            UNICODE_6  INT,
            UNICODE_7  INT,
            UNICODE_8  INT,
            UNICODE_9  INT,
            UNICODE_10  INT,
            LITERAL_1  VARCHAR(1),
            LITERAL_2  VARCHAR(1),
            LITERAL_3  VARCHAR(1),
            LITERAL_4  VARCHAR(1),
            LITERAL_5  VARCHAR(1),
            LITERAL_6  VARCHAR(1),
            LITERAL_7  VARCHAR(1),
            LITERAL_8  VARCHAR(1),
            LITERAL_9  VARCHAR(1),
            LITERAL_10  VARCHAR(1),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(ID),
            INDEX HASH1 USING HASH (HASH_1),
            INDEX HASH2 USING HASH (HASH_2),
            INDEX HASH3 USING HASH (HASH_3),
            INDEX HASH4 USING HASH (HASH_4),
            INDEX HASHALL USING HASH (HASH_1, HASH_2, HASH_3, HASH_4),
            INDEX IDIOM_HASH USING HASH (CONTENT),
            INDEX IDIOM_BTREE USING BTREE (CONTENT),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX UNIC1 USING BTREE (
                        UNICODE_1, 
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR1 USING BTREE (
                        LITERAL_1, 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC2 USING BTREE (
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR2 USING BTREE ( 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC3 USING BTREE (
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR3 USING BTREE (
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC4 USING BTREE (
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR4 USING BTREE (
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC5 USING BTREE (
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR5 USING BTREE (
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC6 USING BTREE (
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR6 USING BTREE (
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC7 USING BTREE (
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR7 USING BTREE (
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC8 USING BTREE (
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR8 USING BTREE (
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC9 USING BTREE (
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR9 USING BTREE (
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC10 USING BTREE (UNICODE_10),
            INDEX LITR10 USING BTREE (LITERAL_10)
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'ALL IDIOM IN USE';
            

-- DROP TABLE IF EXISTS PROVERBE_LIST_LEVEL_0;
CREATE TABLE IF NOT EXISTS 
        PROVERBE_LIST_LEVEL_0 (
            ID         BIGINT NOT NULL AUTO_INCREMENT,
            HASH_1  BIGINT UNSIGNED NOT NULL,
            HASH_2  BIGINT UNSIGNED,
            HASH_3  BIGINT UNSIGNED,
            HASH_4  BIGINT UNSIGNED,
            CONTENT   VARCHAR(20) NOT NULL,
            FREQUENCY  BIGINT,
            FREQ_1     BIGINT,
            FREQ_2     BIGINT,
            FREQ_3     BIGINT,
            FREQ_4     BIGINT,
            FREQ_5     BIGINT,
            NUMB_1     INT,
            NUMB_2     INT,
            NUMB_3     INT,
            NUMB_4     INT,
            NUMB_5     INT,
            RATE_1     DOUBLE(15,12),
            RATE_2     DOUBLE(15,12),
            RATE_3     DOUBLE(15,12),
            RATE_4     DOUBLE(15,12),
            RATE_5     DOUBLE(15,12),
            UNICODE_1  INT NOT NULL,
            UNICODE_2  INT,
            UNICODE_3  INT,
            UNICODE_4  INT,
            UNICODE_5  INT,
            UNICODE_6  INT,
            UNICODE_7  INT,
            UNICODE_8  INT,
            UNICODE_9  INT,
            UNICODE_10  INT,
            UNICODE_11  INT,
            UNICODE_12  INT,
            UNICODE_13  INT,
            UNICODE_14  INT,
            UNICODE_15  INT,
            UNICODE_16  INT,
            UNICODE_17  INT,
            UNICODE_18  INT,
            UNICODE_19  INT,
            UNICODE_20  INT,
            LITERAL_1  VARCHAR(1) NOT NULL,
            LITERAL_2  VARCHAR(1),
            LITERAL_3  VARCHAR(1),
            LITERAL_4  VARCHAR(1),
            LITERAL_5  VARCHAR(1),
            LITERAL_6  VARCHAR(1),
            LITERAL_7  VARCHAR(1),
            LITERAL_8  VARCHAR(1),
            LITERAL_9  VARCHAR(1),
            LITERAL_10  VARCHAR(1),
            LITERAL_11  VARCHAR(1),
            LITERAL_12  VARCHAR(1),
            LITERAL_13  VARCHAR(1),
            LITERAL_14  VARCHAR(1),
            LITERAL_15  VARCHAR(1),
            LITERAL_16  VARCHAR(1),
            LITERAL_17  VARCHAR(1),
            LITERAL_18  VARCHAR(1),
            LITERAL_19  VARCHAR(1),
            LITERAL_20  VARCHAR(1),
            WHEN_INSERT     DATETIME,
            WHEN_UPDATE     DATETIME,
            PRIMARY KEY(ID),
            INDEX HASH1 USING HASH (HASH_1),
            INDEX HASH2 USING HASH (HASH_2),
            INDEX HASH3 USING HASH (HASH_3),
            INDEX HASH4 USING HASH (HASH_4),
            INDEX HASHALL USING HASH (HASH_1, HASH_2, HASH_3, HASH_4),
            INDEX FREQ USING BTREE (FREQUENCY),
            INDEX PROVERBE_HASH USING HASH (CONTENT),
            INDEX PROVERBE_BTREE USING BTREE (CONTENT),
            INDEX UNIC1 USING BTREE (
                        UNICODE_1, 
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR1 USING BTREE (
                        LITERAL_1, 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC2 USING BTREE (
                        UNICODE_2, 
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR2 USING BTREE ( 
                        LITERAL_2, 
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC3 USING BTREE (
                        UNICODE_3,
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR3 USING BTREE (
                        LITERAL_3,
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC4 USING BTREE (
                        UNICODE_4,
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR4 USING BTREE (
                        LITERAL_4,
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC5 USING BTREE (
                        UNICODE_5,
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR5 USING BTREE (
                        LITERAL_5,
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC6 USING BTREE (
                        UNICODE_6,
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR6 USING BTREE (
                        LITERAL_6,
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC7 USING BTREE (
                        UNICODE_7,
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR7 USING BTREE (
                        LITERAL_7,
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC8 USING BTREE (
                        UNICODE_8,
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR8 USING BTREE (
                        LITERAL_8,
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC9 USING BTREE (
                        UNICODE_9,
                        UNICODE_10),
            INDEX LITR9 USING BTREE (
                        LITERAL_9,
                        LITERAL_10),
            INDEX UNIC10 USING BTREE (UNICODE_10),
            INDEX LITR10 USING BTREE (LITERAL_10)
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'ALL PROVERBE IN USE';
      
CREATE TABLE IF NOT EXISTS
            WORD_TYPE_LIST_LEVEL_0 (
                ID BIGINT NOT NULL AUTO_INCREMENT,
                HASH_1 BIGINT UNSIGNED NOT NULL,
                HASH_2 BIGINT UNSIGNED,
                HASH_3 BIGINT UNSIGNED,
                HASH_4 BIGINT UNSIGNED,
                CONTENT VARCHAR(20) NOT NULL,
                TYPE VARCHAR(10) NOT NULL,
                NUMB_1 INT,
                NUMB_2 INT,
                NUMB_3 INT,
                NUMB_4 INT,
                RANK_1 INT NOT NULL,
                RANK_2 INT,
                RANK_3 INT,
                RANK_4 INT,
                RATE_1 DOUBLE(15,12),
                RATE_2 DOUBLE(15,12),
                RATE_3 DOUBLE(15,12),
                RATE_4 DOUBLE(15,12),
                MAJOR_1 VARCHAR(20) NOT NULL,
                MAJOR_2 VARCHAR(20),
                MAJOR_3 VARCHAR(20),
                MAJOR_4 VARCHAR(20),
                MINOR_1 VARCHAR(20) NOT NULL,
                MINOR_2 VARCHAR(20),
                MINOR_3 VARCHAR(20),
                MINOR_4 VARCHAR(20),
                WHEN_INSERT DATETIME,
                WHEN_UPDATE DATETIME NOT NULL,
                PRIMARY KEY(ID),
                INDEX HASH1 USING HASH (HASH_1),
                INDEX CONTENT_HASH USING HASH (CONTENT),
                INDEX CONTENT_BTREE USING BTREE (CONTENT),
                INDEX TYPE_HASH USING HASH (TYPE),
                INDEX TYPE_BTREE USING BTREE (TYPE),
                INDEX RANK_BTREE USING BTREE (RANK_1, RANK_2, RANK_3, RANK_4),
                INDEX SUBJECT USING BTREE (MAJOR_1, MINOR_1, MAJOR_2, MINOR_2, MAJOR_3, MINOR_3, MAJOR_4, MINOR_4)
            ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'TYPE INFO FOR WORDS';

CREATE TABLE IF NOT EXISTS
        WORD_TYPE_INFO (
            CONTENT VARCHAR(20) NOT NULL PRIMARY KEY,
            FREQUENCY BIGINT UNSIGNED DEFAULT 0 COMMENT 'HOW MANY WORDS OF THIS TYPE',
            NUMB_1 INT,
            NUMB_2 INT,
            NUMB_3 INT,
            NUMB_4 INT,
            RANK_1 INT,
            RANK_2 INT,
            RANK_3 INT,
            RANK_4 INT,
            RATE_1 INT,
            RATE_2 INT,
            RATE_3 INT,
            RATE_4 INT,
            INDEX CONTENT USING HASH (CONTENT)
        ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'LIST OF TYPE INFO FOR WORDS';

CREATE TABLE IF NOT EXISTS
        WORD_MAJOR_INFO (
            CONTENT VARCHAR(20) NOT NULL PRIMARY KEY,
            FREQUENCY BIGINT UNSIGNED DEFAULT 0 COMMENT 'HOW MANY WORDS FALL INTO THIS MAJOR',
            NUMB_1 INT,
            NUMB_2 INT,
            NUMB_3 INT,
            NUMB_4 INT,
            RANK_1 INT,
            RANK_2 INT,
            RANK_3 INT,
            RANK_4 INT,
            RATE_1 INT,
            RATE_2 INT,
            RATE_3 INT,
            RATE_4 INT,
            INDEX CONTENT USING HASH (CONTENT)
        ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'LIST OF MAJOR INFO FOR WORDS';
CREATE TABLE IF NOT EXISTS
        WORD_MINOR_INFO (
            CONTENT VARCHAR(20) NOT NULL,
            MAJOR VARCHAR(20) NOT NULL,
            FREQUENCY BIGINT UNSIGNED DEFAULT 0 COMMENT 'HOW MANY WORDS FALL INTO THIS MAJOR',
            NUMB_1 INT,
            NUMB_2 INT,
            NUMB_3 INT,
            NUMB_4 INT,
            RANK_1 INT,
            RANK_2 INT,
            RANK_3 INT,
            RANK_4 INT,
            RATE_1 INT,
            RATE_2 INT,
            RATE_3 INT,
            RATE_4 INT,
            INDEX CONTENT USING HASH (CONTENT),
            INDEX MAJOR USING HASH (MAJOR),
            INDEX CONTENT_BTREE USING BTREE (CONTENT),
            INDEX MAJOR_BTREE USING BTREE (MAJOR),
            INDEX CONJUCTION USING BTREE (MAJOR, CONTENT)
        ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'LIST OF MINOR INFO FOR WORDS';


CREATE TABLE IF NOT EXISTS
        TEXT_WORD_SEGMENT_LIST_LEVEL_0 (
            ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            CONTENT VARCHAR(20) NOT NULL,
            HASH_1 BIGINT UNSIGNED NOT NULL, -- HASH VALUE FOR THE CONTENT
            HASH_2 BIGINT UNSIGNED,
            HASH_3 BIGINT UNSIGNED,
            HASH_4 BIGINT UNSIGNED, -- HASH VALUE FOR THE WHOLE PASSEGE, COMPUTED WITH ALL THE TEXT 
            SERIAL BIGINT UNSIGNED NOT NULL,
            MAJOR VARCHAR(20) NOT NULL,
            MINOR VARCHAR(20) NOT NULL,
            TITLE VARCHAR(20) NOT NULL,
            WHEN_INSERT DATETIME,
            WHEN_UPDATE DATETIME NOT NULL,
            INDEX CONTENT USING BTREE (CONTENT),
            INDEX MAJOR USING BTREE (MAJOR),
            INDEX MINOR USING BTREE (MINOR),
            INDEX TITLE USING BTREE (TITLE)
        )ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'LIST OF WORDS FROM ARTICIFIAL SEGMENTATION';
        
ALTER TABLE TEXT_WORD_SEGMENT_LIST_LEVEL_0 MODIFY HASH_4 BIGINT UNSIGNED COMMENT 'HASH VALUE FOR THE WHOLE PASSEGE, AS IDENTIFIRE';        
CREATE UNIQUE INDEX CONTENT_SERIAL_HASH
        USING BTREE  
        ON  TEXT_WORD_SEGMENT_LIST_LEVEL_0
        (CONTENT, SERIAL, HASH_4);

CREATE TABLE IF NOT EXISTS TRASH (
        ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        CONTENT VARCHAR(100) NOT NULL,
        WHEN_DELETE DATETIME
        )ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'LIST OF WORDS FROM ARTICIFIAL SEGMENTATION';

CREATE TABLE IF NOT EXISTS 
        CHARACTER_WAVE_LIST_LEVEL_0 (
            ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            HASH_1 BIGINT UNSIGNED NOT NULL,
            HASH_2 BIGINT UNSIGNED,
            HASH_3 BIGINT UNSIGNED,
            HASH_4 BIGINT UNSIGNED,
            PINYIN VARCHAR(20) NOT NULL,
            WAVE_HAS INT NOT NULL DEFAULT 0,
            WAVE_BIN MEDIUMBLOB,
            INDEX HASH USING HASH (HASH_1),
            INDEX PY_HASH USING HASH (PINYIN),
            INDEX WH_BTREE USING BTREE (WAVE_HAS)
        )ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'UNICODE-CONTENT-PINYIN-WAVE_BINARY TABLE';

ALTER TABLE CHARACTER_WAVE_LIST_LEVEL_0 ADD COLUMN WAVEFILE VARCHAR(100) NOT NULL;
-- ALTER TABLE CHARACTER_WAVE_LIST_LEVEL_0 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;



CREATE TABLE IF NOT EXISTS
        LOGGING_SYSTEM (
            ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            NUM_1 INT COMMENT 'DUMPLIST.COUNT',
            NUM_2 INT COMMENT 'INITLIST.COUNT',
            NUM_3 INT COMMENT 'TOTALLIST.COUNT',
            NUM_4 INT,
            NUM_5 INT,
            NUM_6 INT,
            NUM_7 INT,
            NUM_8 INT,
            NUM_9 INT,
            NUM_10 INT,
            RATE_1 FLOAT, -- DURATION
            RATE_2 FLOAT,
            RATE_3 FLOAT,
            RATE_4 FLOAT,
            RATE_5 FLOAT,
            RATE_6 FLOAT,
            RATE_7 FLOAT,
            RATE_8 FLOAT,
            RATE_9 FLOAT,
            RATE_10 FLOAT,
            STRING_1 MEDIUMTEXT COMMENT 'DUMPLIST',
            STRING_2 MEDIUMTEXT COMMENT 'INITLIST',
            STRING_3 MEDIUMTEXT COMMENT 'TOTALLIST',
            STRING_4 MEDIUMTEXT,
            STRING_5 MEDIUMTEXT,
            STRING_6 MEDIUMTEXT,
            STRING_7 MEDIUMTEXT,
            STRING_8 MEDIUMTEXT,
            STRING_9 MEDIUMTEXT,
            STRING_10 MEDIUMTEXT,
            LOG_TEXT LONGTEXT,
            WHEN_INSERT DATETIME NOT NULL,
            WHEN_UPDATE DATETIME NOT NULL            
        ) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE utf8_bin COMMENT 'SYSTEM LOGS';